### ISSUE TITLE
Update vendors 

### ISSUE THREAD

**Issue by anoopwebs** [caicloud/event_exporter#14]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
 
kind feature

**What happened**:
Vendor are getting old and last update in 3 years. Can we get it updated?

**What you expected to happen**:
Updated Vendors

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by anoopwebs** [comment]
@supereagle What do you think about it?

**Comment by supereagle** [comment]
I will update k8s to v1.14, is it ok?

**Comment by anoopwebs** [comment]
I'd say go for it, hoping that has backward compatibility at least up to 1.10

**Comment by anoopwebs** [comment]
@supereagle Hows this work going?

**Comment by supereagle** [comment]
> @supereagle Hows this work going?

Still wip, many codes need to be updated.
