### ISSUE TITLE
Question: Why not report the timestamp

### ISSUE THREAD

**Issue by seglo** [caicloud/event_exporter#18]
/kind feature

I'm interested in using this project, but I need to find a way to maintain order of events that are scraped in the same interval.  For monitoring purposes the scrape timestamp is good enough, but if multiple events are created within a scrape interval it would be nice to have the option to sort them chronologically.

I want to be able to replay events in a timeseries way in my monitoring solution.  If prometheus isn't appropriate for this do you have any suggestions on what to backup events to for analytics purposes?

**Comment by lichuan0620** [comment]
@seglo I cannot think of a way to make this work. As the developers of Prometheus themselves suggested, Prometheus is not an event-based monitoring solution. It is good at telling you what happened during a period of time with 99.9% precision, not what exactly happened at a specified point of time. 

If you want event-based monitoring with the ability to search and sort the Events, or even look up each individual Event, try ElasticSearch. I personally use Prometheus for alerting and monitoring, and ElasticSearch for full-text searching historical Events.

**Comment by seglo** [comment]
@lichuan0620 Thanks for your feedback.  I agree ES is probably the easiest solution to use for these time series event analytics.  I'll consider how I can use this information in Prometheus and if it actually makes sense for my use case.
