### ISSUE TITLE
Major Release Proposal (v1.0)

### ISSUE THREAD

**Issue by lichuan0620** [caicloud/event_exporter#37]
#28 has exposed a serious bug in our current design.

We are currently grouping events by the following labels:

| label | from |
|:--- |:--- |
|event_namespace |event.InvolvedObject.Namespace |
|event_name |event.InvolvedObject.Name |
|event_kind |event.InvolvedObject.Kind |
|event_reason |event.Reason |
|event_type |event.Type |
|event_subobject |event.InvolvedObject.FieldPath |
|event_message |event.Message
|event_source | event.Source.Host/event.Source.Component |

Due to the absence of both `event.Name` and `event.UID`, if one object produced multiple events with the same reason and error message at the same time, then our code would attempt to expose multiple metrics with identical label set and #28 would happen. 

#36 attempted to address this problem by adding an `event_metaname` label. This would fix the problem, but it would make the label names confusing. It's not immediately obvious for what do `event_metaname` and `event_name` stand. Another problem related to label naming is that Kubernetes has adopted a [new metrics design best practice](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/instrumentation.md) and a [metrics overhaul](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20181106-kubernetes-metrics-overhaul.md) was implemented in Kubernetes 1.14. Our naming practice doesn't fit the standard.

For the reasons explained above, I propose that we release a major release (v1.0) that completely redefine the metrics. The code would use a clean up in the process as well. We could test the changes alone side Compass 2.11.0 (which is also going through a non-compatible metric overhaul), and release event_exporter v1.0.0 as soon as Compass 2.11.0.

**Comment by lichuan0620** [comment]
/cc @supereagle @jianglinjian @ddysher 

note: please keep Compass related discussion internal and out of this issue

**Comment by ddysher** [comment]
When will both involved objects' name and UID be empty?
> Due to the absence of both event.Name and event.UID

Generally LGTM. Looks like there are folks using this exporter, we should clearly document the incompatibility, if any.

**Comment by lichuan0620** [comment]
> When will both involved objects' name and UID be empty?

It's not that they are empty; the problem is we never put them in the label set, so our label set don't always uniquely identify every event.

**Comment by lichuan0620** [comment]
will implement in Q3 this year and hopefully release before Q4

**Comment by lichuan0620** [comment]
v1.0.0 is now tested and buildable on the master branch
