### ISSUE TITLE
Feature request: OOM or cpu limit events

### ISSUE THREAD

**Issue by danielmotaleite** [caicloud/event_exporter#44]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

I think it is a feature, but don't even know if it is possible :)

**What happened**:
My K8s setup was having a Pod OOM and another with a CPU limit. I was expecting that the k8s event showed those events, but all i could see was the healtcheck failure.

**What you expected to happen**:
Some k8s event for when the pod limits are trigger

**How to reproduce it (as minimally and precisely as possible)**:
Set a pod with low memory and cpu limit and start it up

**Anything else we need to know?**:
i'm currently in k8s 1.15

**Comment by lichuan0620** [comment]
`event_exporter` exports the k8s Events as they were; it doesn't alter them or creates new Events. You could implement those Events on your own (I won't go into this topic as it could be quite an essay), and `event_exporter` should be able to pick them up.

If you were able to see those Events but don't see `event_exporter` exposing the metrics, feel free to create a bug issue

**Comment by danielmotaleite** [comment]
So it is really a k8s limitation, the event isn't simply there! roger that! closing this then
