### ISSUE TITLE
pull v1.0 - manifest unkown

### ISSUE THREAD

**Issue by yonimoses** [caicloud/event_exporter#45]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
trying to pull the v1.0 as states in the deploy.yml ended in 
Error response from daemon: manifest for caicloud/event-exporter:v1.0.0 not found: manifest unknown: manifest unknown
i'm guessing you haven't release it yet..?

If that's the case - it the src buildable in master brach? 

thanks!

**Comment by lichuan0620** [comment]
We haven't released it. We've only tested in our dev environment. We will release it after using it for a while in production.

The master is ready and buildable, try `REGISTRY=someregistry VERSION=v1.0.0 make container`

**Comment by lichuan0620** [comment]
The following image has been released:

```
caicloud/event-exporter:v1.0.0
caicloud/event-exporter:v1.0
caicloud/event-exporter:latest
```

/close
