### ISSUE TITLE
Event message no longer included as label in v1.0.0

### ISSUE THREAD

**Issue by sebradloff** [caicloud/event_exporter#49]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Potential bug report/regression or a feature request depending on motivations for v1.0.0

> Uncomment only one, leave it on its own line:
>
> kind bug

**What happened**:
The event message is no longer exported as a label.

I believe it was lost in the refactoring. I'm not sure if this was on purpose or by mistake.
This looks like the line in the PR where the `event_message` used to be: https://github.com/caicloud/event_exporter/pull/43/files#diff-ed648181f98484bd12541509e0ae7b5ad1d1de7674ab1721814b47ddd5c95de4L49

With the new implementation of the event metric defined here: https://github.com/caicloud/event_exporter/pull/43/files#diff-56f9d3288b78a9692046117d91600fe9b201066802b9db18b7f59d283808cd39R154
The message is now no longer present.

**What you expected to happen**:
I would expect message to be a label on the event metric that we could then pattern match with alerting rules.

**Anything else we need to know?**:
Like I said, I'm not sure if this is by design or not for v1.0.0 refactor.

**Comment by lichuan0620** [comment]
It was on purpose. 

Info-like data such as event message make bad metric labels. Including them could result in very high cardinality, and doesn't suit the typical use case of metrics data. 

If you absolutely need entire Event objects, I'd personally recommend using a log-like system such as Elasticsearch.
