### ISSUE TITLE
Exporting specific events (filter by specific Event Reasons)

### ISSUE THREAD

**Issue by EliMutchnik** [caicloud/event_exporter#51]
/kind feature

Is there a way today to specify a filter of Event reasons to the collector and generate only those metrics?
**For example:** I want this tool to export metrics only for Reason="OOMKilled" events.

Is it possible? what code changed need to be done to achieve this?
Thanks!

**Comment by lichuan0620** [comment]
filtering metrics data is usually done on the Prometheus side, using relabeling with `drop` or `keep` action. This [doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) has more details.

/close
